x-indexer: &indexer-base
  image: oct8
  restart: always
  volumes:
    - ./config/config_user_transcations_new.yaml:/app/config/config.yaml
  networks:
    - aptos-network
    - default
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "3"

  deploy:
    resources:
      limits:
        cpus: "6"
        memory: "25g"

  command: ["--config-path", "/app/config/config.yaml"]

x-indexer-changes: &indexer-base-changes
  build:
    context: ./rust
    dockerfile: Dockerfile
  restart: always
  volumes:
    - ./config/config_tnx_changes.yaml:/app/config/config.yaml

  networks:
    - aptos-network
    - default
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "3"

  deploy:
    resources:
      limits:
        cpus: "6"
        memory: "25g"

  command: ["--config-path", "/app/config/config.yaml"]

x-indexer-changes-diffs: &indexer-base-changes-diffs
  build:
    context: ./rust
    dockerfile: Dockerfile
  restart: always
  volumes:
    - ./config/config_tnx_changes_diffs.yaml:/app/config/config.yaml

  networks:
    - aptos-network
    - default
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "3"

  deploy:
    resources:
      limits:
        cpus: "6"
        memory: "25g"

  command: ["--config-path", "/app/config/config.yaml"]


x-indexer-modules-changes: &indexer-base-modules-changes
  build:
    context: ./rust
    dockerfile: Dockerfile
  restart: always
  volumes:
    - ./config/config_tnx_changes_modules.yaml:/app/config/config.yaml

  networks:
    - aptos-network
    - default
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "3"

  deploy:
    resources:
      limits:
        cpus: "6"
        memory: "25g"

  command: ["--config-path", "/app/config/config.yaml"]

x-indexer-ans: &indexer-base-ans
  build:
    context: ./rust
    dockerfile: Dockerfile
  restart: always
  volumes:
    - ./config/config_ans.yaml:/app/config/config.yaml
    - ./ssl_cert:/app/ssl_cert

  network_mode: "host"
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "3"

  deploy:
    resources:
      limits:
        cpus: "6"
        memory: "25g"

  command: ["--config-path", "/app/config/config.yaml"]


x-indexer-events: &indexer-base-events
  image: oct8
  restart: always
  volumes:
    - ./config/config_events.yaml:/app/config/config.yaml
  networks:
    - aptos-network
    - default
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "3"

  deploy:
    resources:
      limits:
        cpus: "6"
        memory: "25g"

  command: ["--config-path", "/app/config/config.yaml"]




services:
  rust-indexer-changes:
    <<: *indexer-base-changes
    environment:
      RUNNER_ID: 0
      AUTH_TOKEN: aptoslabs_f8QKqfRTFo2_AfiDo3ZFEyTVpfU3qt4WC75GNb7gU3H1x

  rust-indexer-changes-diffs:
    <<: *indexer-base-changes-diffs
    environment:
      RUNNER_ID: 0
      AUTH_TOKEN: aptoslabs_f8QKqfRTFo2_AfiDo3ZFEyTVpfU3qt4WC75GNb7gU3H1x


  rust-indexer-modules-changes:
    <<: *indexer-base-modules-changes
    environment:
      RUNNER_ID: 0
      AUTH_TOKEN: aptoslabs_f8QKqfRTFo2_AfiDo3ZFEyTVpfU3qt4WC75GNb7gU3H1x


  rust-indexer-events:
    <<: *indexer-base-events
    environment:
      RUNNER_ID: 0
      AUTH_TOKEN: aptoslabs_f8QKqfRTFo2_AfiDo3ZFEyTVpfU3qt4WC75GNb7gU3H1x

  rust-indexer-ans:
    <<: *indexer-base-ans
    environment:
      RUNNER_ID: 0
      AUTH_TOKEN: aptoslabs_f8QKqfRTFo2_AfiDo3ZFEyTVpfU3qt4WC75GNb7gU3H1x

  rust-indexer-events-old:
    <<: *indexer-base-events
    environment:
      RUNNER_ID: 1
      AUTH_TOKEN: aptoslabs_f8QKqfRTFo2_AfiDo3ZFEyTVpfU3qt4WC75GNb7gU3H1x


  # rust-indexer-1:
  #   <<: *indexer-base
  #   environment:
  #     RUNNER_ID: 1
  #     AUTH_TOKEN: aptoslabs_fv8NiQf6hgS_PrPYYcR7P4ncgXmnLa5XECqF3VNbP4qjd

  rust-indexer-2:
    <<: *indexer-base
    environment:
      RUNNER_ID: 2
      AUTH_TOKEN: aptoslabs_i33Aq9YZvCM_DPzuSvjuoxT7whQDiZd2nCTZi6C4wbDrU

  rust-indexer-3:
    <<: *indexer-base
    environment:
      RUNNER_ID: 3
      AUTH_TOKEN: aptoslabs_HW99Hjfx4Rv_146A817vYhp5Zha3RVwZ7x9CycRWLmfHL

  index-processor-coins-python:
    build: ../../indexer/web3-security/indexer/python/
    restart: always
    environment:
      DB_CONNECTION_URI: postgresql://dbadmin:CvGbESSqy428OEza96VPVkO9FFs2F8@postgres-public.cyt0fqqed8cg.eu-west-1.rds.amazonaws.com:5432/postgres
      AUTH_TOKEN: ${AUTH_TOKEN}
    volumes:
      - ../../indexer/web3-security/indexer/config/config_custom_processor.yaml:/app/config/config.yaml
    networks:
      - aptos-network
      - default
    ports:
      - "8085:8085"
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "2g"

  mongo-new:
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=5zd8xjwpzC3OawFaaB2o5l3BlyTvFYTo
      - MONGO_COLLECTION=coin_data
      - INSERT_EXAMPLE_DATA=True  # Change to False to skip data insertion
    ports:
      - "27017:27017"
    volumes:
      - indexer_mongo-new-data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d/02-init-mongo.js
      - ./init-mongo-coins.js:/docker-entrypoint-initdb.d/01-init-mongo-coins.js
      - ./CvGbESSqy428OEza96VPVkO9FFs2F8_data/tx_metadata_server.json:/data/tx_metadata_server.json
      - ./CvGbESSqy428OEza96VPVkO9FFs2F8_data/tx_data_server.json:/data/tx_data_server.json
      - ./CvGbESSqy428OEza96VPVkO9FFs2F8_data/final_results_server.json:/data/final_results_server.json
      - ./mongod.conf:/etc/mongod.conf

    # command: --auth --bind_ip_all
    networks:
      - aptos-network
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "30"  # Limit to 25% of a single CPU core
          memory: "70g"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db-test:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=CvGbESSqy428OEza96VPVkO9FFs2F8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

    ports:
      - "5434:5432"
    volumes:
      - indexer_pgdata3:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      # - ./potgres.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - aptos-network
      - default

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

    deploy:
      resources:
        limits:
          cpus: "24"  # Limit to 25% of a single CPU core
          memory: "250g"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

    ports:
      - "3307:3306"
    volumes:
      - indexer_mysql-data:/var/lib/mysql
      - ./init-mysql:/docker-entrypoint-initdb.d
    networks:
      - aptos-network
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.25"  # Limit to 25% of a single CPU core
          memory: "1g"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  aptos-network:
    driver: bridge
    external: true

volumes:
  indexer_mongo-new-data:
    external: true
  indexer_pgdata3:
    external: true
  indexer_mysql-data:
    external: true
