health_check_port: 8087
server_config:
  processor_config:
    type: fungible_asset_processor
  postgres_connection_string: postgresql://postgres:example@db-test:5432/postgres
  indexer_grpc_data_service_address: https://grpc.mainnet.aptoslabs.com:443
  auth_token: aptoslabs_fv8NiQf6hgS_PrPYYcR7P4ncgXmnLa5XECqF3VNbP4qjd
  enable_verbose_logging: true


